import React from 'react';

import CoinPage from 'layout/CoinPage';

const pageInfo = {
  meta: {
    url: 'https://guardarian.com/buy-sushi',
    title: 'Buy Sushi (SUSHI) | Buy SUSHI with Fiat, EUR & USD',
    description:
      'Guardarian offers the most user-friendly environment for purchasing the Sushi coin. Get the best EUR & USD to SUSHI exchange rate at Guardarian.',
    image: 'https://guardarian.com/services/sell-crypto-mobile.png',
  },
  banner: {
    title: 'Buy Sushi Swap (SUSHI)',
    text: 'SushiSwap is a fork of Uniswap with several key differences, in particular with the SUSHI token. When launched, the token serves two functions: granting the holders control rights and a portion of the fees paid to the protocol. Simplified, SUSHI holders "own" the protocol.',
    info: {
      release: 2020,
      ticker: 'SUSHI',
      creator: 'Chef Nomi',
    },
    theme: 'sushi',
    currency: 'sushi',
  },
  about: {
    articles: [
      {
        title: 'What is  Sushi Swap (SUSHI)?',
        text: 'SushiSwap is a hard fork of Uniswap with additional community-oriented features, while retaining the root design of its parent element. Unfortunately, instead of going its own way, the protocol tries to get liquidity from its parent project.',
      },
      {
        title: 'Why to buy Sushi Swap (SUSHI)?',
        text:
          'At Uniswap, liquidity providers make money on the trading fees charged online. Smaller liquidity providers risk being overshadowed by large cryptocurrency exchanges, mining pools and other wealthy providers.\n' +
          '\n' +
          'But its byproduct tends to improve it by providing more incentives. Here, liquidity providers are rewarded with SUSHI tokens. Providers earn a portion of the transaction fees generated by the system, even when they stop providing liquidity.\n',
      },
    ],
    theme: 'sushi',
  },
  exchange: {
    currency: 'sushi',
    network: 'ETH',
    name: 'Sushi Swap',
    usdImageSrc: '/sushi/usd-sushi.png',
    eurImageSrc: '/sushi/eur-sushi.png',
    eurText: '',
    usdText: '',
  },
  howToBuy: {
    name: 'Sushi Swap',
    ticker: 'SUSHI',
    youtube: 'https://www.youtube.com/embed/dxHo0Y3xydw',
  },
};

export default function index() {
  return <CoinPage pageInfo={pageInfo} />;
}
